---
mysql_version: '5.7'
mysql_ha: 'none' 
# master-slave, 
# master-master-slave, 
# dual-master, 
# mmm, 
# mha, 
# cluster, 
# fabric 
# mmm-cluster, 
# pxc

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '10.0.0.181'       # 内网 IP   
      NAME: 'mysql-1'
      BIND_ADDRESS: '0.0.0.0'  # 内网 IP
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      LOGDIR: '/var/log/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'
      PORT: 3306
      ENGINE: 'InnoDB'
      IS_MASTER: yes                        # 一级 MYSQL , 是别的 SLAVE 的 MASTER 大部分 主机 log-slave-updates = 1
      CONNECTIONS:
        - drop_user: false                 # index = 0, 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
            - '127.0.0.1'
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true                 # index = 1
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true                 # index = 2
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
 
        - drop_user: false               # index = 8
          with_grant_option: true
          GRANTS:
            - 'RELOAD'
            - 'LOCK TABLES'
            - 'REPLICATION CLIENT'
            - 'CREATE TABLESPACE'
            - 'PROCESS'
            - 'SUPER'
          USER: 'backup'
          HOSTS: 
            - 'localhost'                 # 提供 xtrabuckup shell  连取 127.0.0.1 ，在 localhost
            - '10.0.0.21'                 # 提供 xtrabuckup shell  连取 127.0.0.1 ，在 Ansilbe 主机
          PASSWORD: 'mysql_pass_backup'
          DATABASE: '*'