---
mysql_version: 5.7
mysql_create_databases: 'landan,vpn'
mysql_ha: 'mgr' 

MYSQL:
  MASTERHA:
    VIP: '10.0.0.180/24'
    CONF: '/etc/masterha/app.cnf'
    MANAGER_LOG: '/var/log/masterha/masterha.log'
  GTID_MODE: yes
  CHARACTER_SET: 'utf8mb4'
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  COLLATION: 'utf8mb4_unicode_ci'
  MASTER: '192.168.1.2'
  POSITION: 8372
  SERVERS:
    - HOST: '192.168.1.2'       # 内网 IP   
      NAME: 'mysql-1'
      BIND_ADDRESS: '0.0.0.0'  # 内网 IP
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      LOGDIR: '/var/log/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'
      PORT: 3306
      ENGINE: 'InnoDB'
      LOOSE_GROUP_REPLICATION_LOCAL_ADDRESS: '192.168.1.2:33601'
      LOOSE_GROUP_REPLICATION_GROUPS_SEEDS: ' 192.168.1.2:33601,192.168.1.8:33601'
      CONNECTIONS:
        - drop_user: false                 # index = 0, 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
            - '127.0.0.1'
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true                 # index = 1
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true                 # index = 2
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true                 # index = 3
          with_grant_option: true
          GRANTS: 
            - 'REPLICATION CLIENT'
          USER: 'monitor'
          HOSTS: 
            - '10.0.0.171'                 # 提供 MHA manager 从 10.0.0.171  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_monitor'
          DATABASE: '*'
        - drop_user: true                 # index = 4
          with_grant_option: true
          GRANTS: 
            - 'SUPER'
            - 'RELOAD'
            - 'REPLICATION CLIENT'
            - 'SELECT'
            - 'CREATE'
            - 'INSERT'
            - 'UPDATE'
            - 'DELETE'
            - 'DROP'
          USER: 'masterha'
          HOSTS: 
            - '10.0.0.172'                 # 提供 MHA manager 从 10.0.0.172  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_masterha'
          DATABASE: '*'
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
          PASSWORD: 'mysql_pass_backend_1B40E5312B2A2B47B0390F8F8AE00B7C'
          DATABASE: '*'
        - drop_user: true                # index = 6
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  

          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'          
          
        - drop_user: true                # index = 7
          with_grant_option: false
          GRANTS: 
            - 'SUPER'
            - 'REPLICATION CLIENT'
            - 'PROCESS'
          USER: 'agent'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
  
          PASSWORD: 'mysql_pass_agent'
          DATABASE: '*'
                 
        - drop_user: false               # index = 8
          with_grant_option: true
          GRANTS:
            - 'RELOAD'
            - 'LOCK TABLES'
            - 'REPLICATION CLIENT'
            - 'CREATE TABLESPACE'
            - 'PROCESS'
            - 'SUPER'
          USER: 'backup'
          HOSTS: 
            - 'localhost'                 # 提供 xtrabuckup shell  连取 127.0.0.1 ，在 localhost
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  

          PASSWORD: 'mysql_pass_backup'
          DATABASE: '*'
          
    - HOST: '192.168.1.8'       # 外网 IP   # 次一级 MYSQL 
      NAME: 'mysql-2'
      BIND_ADDRESS: '0.0.0.0' # 内网 IP
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      LOGDIR: '/var/log/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'
      PORT: 3306
      ENGINE: 'InnoDB'
      LOOSE_GROUP_REPLICATION_LOCAL_ADDRESS: '192.168.1.2:33601'
      LOOSE_GROUP_REPLICATION_GROUPS_SEEDS: ' 192.168.1.2:33601,192.168.1.8:33601'
      CONNECTIONS:
        - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
            - '127.0.0.1'
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'REPLICATION CLIENT'
          USER: 'monitor'
          HOSTS: 
            - '10.0.0.171'                 # 提供 MHA manager 从 10.0.0.171  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_monitor'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'SUPER'
            - 'RELOAD'
            - 'REPLICATION CLIENT'
            - 'SELECT'
            - 'CREATE'
            - 'INSERT'
            - 'UPDATE'
            - 'DELETE'
            - 'DROP'
          USER: 'masterha'
          HOSTS: 
            - '10.0.0.172'                 # 提供 MHA manager 从 10.0.0.172  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_masterha'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
     
          PASSWORD: 'mysql_pass_backend_1B40E5312B2A2B47B0390F8F8AE00B7C'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  

          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'          
          
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'SUPER'
            - 'REPLICATION CLIENT'
            - 'PROCESS'
          USER: 'agent'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
 
          PASSWORD: 'mysql_pass_agent'
          DATABASE: '*'
                 
        - drop_user: false                  
          with_grant_option: true
          GRANTS:
            - 'RELOAD'
            - 'LOCK TABLES'
            - 'REPLICATION CLIENT'
            - 'CREATE TABLESPACE'
            - 'PROCESS'
            - 'SUPER'
          USER: 'backup'
          HOSTS: 
            - 'localhost'                 # 提供 xtrabuckup shell  连取 127.0.0.1 ，在 localhost
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
          PASSWORD: 'mysql_pass_backup'
          DATABASE: '*'     
          
    - HOST: '10.0.0.193'       # 外网 IP    # 次一级 MYSQL 
      NAME: 'mysql-3'
      BIND_ADDRESS: '0.0.0.0' # 内网 IP
      DATADIR: '/var/lib/mysql'
      BASEDIR: '/var/lib/mysql'
      LOGDIR: '/var/log/mysql'
      SOCKET: '/var/lib/mysql/mysql.sock'
      PORT: 3306
      ENGINE: 'InnoDB'
      LOOSE_GROUP_REPLICATION_LOCAL_ADDRESS: '192.168.1.2:33601'
      LOOSE_GROUP_REPLICATION_GROUPS_SEEDS: ' 192.168.1.2:33601,192.168.1.8:33601'
      CONNECTIONS:
        - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
            - '127.0.0.1'
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOSTS: 
            - '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'REPLICATION CLIENT'
          USER: 'monitor'
          HOSTS: 
             - '10.0.0.171'                 # 提供 MHA manager 从 10.0.0.171  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_monitor'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'SUPER'
            - 'RELOAD'
            - 'REPLICATION CLIENT'
            - 'SELECT'
            - 'CREATE'
            - 'INSERT'
            - 'UPDATE'
            - 'DELETE'
            - 'DROP'
          USER: 'masterha'
          HOSTS: 
             - '10.0.0.172'                 # 提供 MHA manager 从 10.0.0.172  连取 10.0.0.191 ，在 VM 外网
          PASSWORD: 'mysql_pass_masterha'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  

          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'          
          
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'SUPER'
            - 'REPLICATION CLIENT'
            - 'PROCESS'
          USER: 'agent'
          HOSTS: 
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
   
          PASSWORD: 'mysql_pass_agent'
          DATABASE: '*'
                 
        - drop_user: false                  
          with_grant_option: true
          GRANTS:
            - 'RELOAD'
            - 'LOCK TABLES'
            - 'REPLICATION CLIENT'
            - 'CREATE TABLESPACE'
            - 'PROCESS'
            - 'SUPER'
          USER: 'backup'
          HOSTS: 
            - 'localhost'                 # 提供 xtrabuckup shell  连取 127.0.0.1 ，在 localhost
            - '192.168.1.%'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost  
          PASSWORD: 'mysql_pass_backup'
          DATABASE: '*'

          
  DATADIR: '/var/lib/mysql'
  BASEDIR: '/var/lib/mysql'
  CREATE_DATABASES:
    - landan
    - vpn
    - lorentz
    - chatshier
    - lottery
    - legeo
    - cms