--- # 优先次序高
php_version: '5.6'
PHP:
  ERROR_REPORTING: 'E_ALL'
  SESSION:
    SAVE_HANDLER: 'memcached'
    SAVE_PATH: '127.0.0.1:11211'
  FPM:
    PM: 'dynamic'  # DEV PHP MYSQL REDIS 共用 適合 dynamic
    MAX_CHILDREN: 50
    START_SERVERS: 20
    MIN_SPARE_SERVERS: 10
    MAX_SPARE_SERVERS: 30
  XDEBUG:
    REMOTE_CONNECT_BACK: 0
    REMOTE_HOST: '127.0.0.1'
