--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'fea.lives2-yc-test0708.xyz www.fea.lives2-yc-test0708.xyz fea.lives3-yec-sto07test.xyz www.fea.lives3-yec-sto07test.xyz'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'

mysql_version: '5.6'      
MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '10.0.0.181'       # 内网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 

            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend'
          DATABASE: 'shoushou_video'



           


