--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'yecao-7k8s.xyz lives3-yec-sto07k8.xyz www.yecao-7k8s.xyz www.lives3-yec-sto07k8.xyz'
      INDEX: 'index.php index.html index.htm'

      
mysql_version: '5.6'      

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '192.168.1.2'       # 内网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost
            - '192.168.1.7'              # PHP       
          PASSWORD: 'mysql_pass_backend_81DB5D046334FBDB962D1E7DB38383B4'
          DATABASE: 'shoushou_video'



           


