--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'hdalvik.club www.hdalvik.club'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'
      ALLOW: '27.110.131.153'
      

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '47.242.59.96'       # 外网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:

        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'DELETE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'LOCK TABLES'
            - 'TRIGGER'
            - 'REFERENCES'
            - 'EVENT'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend'
          DATABASE: 'shoushou_video'