--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'lives3-yc-07ks.xyz lives3-yc-07bp.xyz lives3-yc-sto07k8.xyz lives3-yc-sto07bp.xyz'
      INDEX: 'index.php index.html index.htm'
      # 根據 2020 CORS 策略, 瀏覽器 在請求 不同域名 且 具有 post 字節 時候,  瀏覽器 會 預先打 一個 options 請求
      # 錯誤解法 把 post 值 轉為 query, 這個 不符合 cors 策略 減低 API 彈性
      # 正確解法 首先 options 回 204 (試打立即回應 空), 且 Access-Control-Max-Age' 86400 (設定 試打的有效時間 為 1 day

      # CORS 寫在 Nginx 的優點是 效能優, 避免 Go-Gin, PHP-laravel, Node-Koa 同一個機制要寫出數次, 找到的 middleware 也不一定完全相同
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"  #表明 Server 是否允許發送Cookie，預設是 False。如果要發送Cookie，Access-Control-Allow-Origin 就不能設為 * ，就必須要明確指定
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        # Nginx HTTP 可以在 跨域请求时候 可以 接受的 header
        # 已 JWT 为例， 就需要开启 Authorization
        - "'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"

      PHP: '7.3'
      REWRITE: 1
      TRY_FILES: '$uri $uri/ /index.php?$query_string'

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/dist'
      SERVER_NAME: 'yecao09.me www.yecao09.me yehua09.com www.yehua09.com ~^(www\.)?(?<domain>.+)$'
      REDIRECT: 1
      INDEX: 'www_index.html www_index.htm'
      REWRITE: 0
      TRY_FILES: '$uri $uri/ /www_index.html?$query_string'
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/dist'
      SERVER_NAME: 'm.yecao09.me m.yehua09.com ~^(m\.)(?<domain>.+)$'
      REDIRECT: 1
      INDEX: 'm_index.html m_index.htm'
      REWRITE: 0
      TRY_FILES: '$uri $uri/ /m_index.html?$query_string'
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"


    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_koa/'
      SERVER_NAME: 'api.yecao09.me api.yehua09.com ~^(api\.)(?<domain>.+)$'
      INDEX: 'index.htm'
      REWRITE: 0
      PROXY_PASS: 'http://127.0.0.1:4003$request_uri'
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"






    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_golang/dist'
      SERVER_NAME: 'api.yecdis-pro.xyz'
      INDEX: 'index.html index.htm'
      PROXY_PASS: 'http://shoushou_video_golang_servers'
      UPSTREAM:
        NAME: 'shoushou_video_golang_servers'
        SERVERS:
          - '127.0.0.1:4011'
          - '127.0.0.1:4012'
          - '127.0.0.1:4013'
          - '127.0.0.1:4014'
          - '127.0.0.1:4015'
          - '127.0.0.1:4016'
          - '127.0.0.1:4017'
          - '127.0.0.1:4018'
      REWRITE: 0

      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_domain_react/dist'
      SERVER_NAME: 'admin.yecdis-pro.xyz'
      INDEX: 'index.html index.htm'
      REWRITE: 0
      LOCATION: '~ ^/(\w+)'
      TRY_FILES: '$uri $uri/ /$1/index.html'
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        - "'Access-Control-Allow-Origin' '$http_origin'"
        - "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"


    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_domain_socketio/dist'
      SERVER_NAME: 'socket.yecdis-pro.xyz'
      INDEX: 'index.html index.htm'
      PROXY_PASS: ' http://127.0.0.1:4002$request_uri'
      REWRITE: 0
      ADD_HEADERS:
        - "X-Frame-Options 'SAMEORIGIN'"
        - "X-XSS-Protection '1; mode=block'"
        - "X-Content-Type-Options 'nosniff'"
        # SOCKET IO 有自備 CORS 所以 NGINX 不需要
        #- "'Access-Control-Allow-Origin' '*'"
        #- "'Access-Control-Allow-Credentials' 'true'"
        - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
        - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"



   # - HTTP_PORT: 80
    #   ROOT: '/var/www/dl_lottery_js/dist'
    #   SERVER_NAME: 'dal02.xyz *.dal02.xyz'
    #   REDIRECT: 0
    #   INDEX: 'index.html index.htm'
    #   REWRITE: 0
    #   TRY_FILES: '$uri $uri/ /index.html?$query_string'
    #   ADD_HEADERS:
    #     - "Accept-Ranges 'bytes'"
    #     - "X-Frame-Options 'SAMEORIGIN'"
    #     - "X-XSS-Protection '1; mode=block'"
    #     - "X-Content-Type-Options 'nosniff'"
    #     - "'Access-Control-Allow-Origin' '$http_origin'"
    #     - "'Access-Control-Allow-Credentials' 'true'"
    #     - "'Access-Control-Max-Age' 86400"             # 本次 Preflight Request 的有效期限，以秒為單
    #     - "'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS'"
    #     - "'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'"




    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh10.xyz *.yh10.xyz'
    #   INDEX: 'news_index.html news_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/dist'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh11.xyz *.yh11.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201058'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh12.xyz *.yh12.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201054'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh13.xyz *.yh13.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201662'
    # - HTTP_PORT: 80
    #   SERVER_NAME: 'yh1201.xyz *.yh1201.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201054'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh1202.xyz *.yh1202.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201662'

    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yeh120.com yeh124.com yeh125.com yh1212.live yh1213.live yh1214.live     *.yeh120.com *.yeh124.com *.yeh125.com *.yh1212.live *.yh1213.live *.yh1214.live'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.yecao07.me/?code=201054'

    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yh15.xyz *.yh15.xyz'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    # #   RETURN: '301 $scheme://www.yecao07.me/?code=201049'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'se-yh02.xyz *.se-yh02.xyz'
    #   INDEX: 'menu.html menu.htm'
    #   REWRITE: 0

    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'se-yh03.xyz se-yh030.xyz *.se-yh03.xyz *.se-yh030.xyz'
    #   INDEX: 'sepang.html sepang.htm'
    #   REWRITE: 0

    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'se-yh05.xyz *.se-yh05.xyz *.se-yh050.xyz se-yh050.xyz'
    #   INDEX: 'sesirui.html sesirui.htm'
    #   REWRITE: 0


    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'yeh121.com *.yeh121.com'
    #   INDEX: 'heiliaowang.htm heiliaowang.html'
    #   REWRITE: 0

    # - HTTP_PORT: 80
    #   ROOT: '/var/www/aoa-yh-agent-h5/dist'
    #   SERVER_NAME: '*.aoa06.me aoa06.me'
    #   INDEX: 'index.html index.htm'
    #   REWRITE: 0

      # RETURN: '301 $scheme://yehua07.com/seroot'
    # - HTTP_PORT: 80
    #   ROOT: '/var/www/shoushou_download_js/dist'
    #   SERVER_NAME: 'aoa7.me *.aoa7.me'
    #   INDEX: 'www_index.html www_index.htm'
    #   REWRITE: 0
    #   RETURN: '301 $scheme://www.aoabet9730.com'



RABBITMQ:
  VHOST: 'shoushou_video'
  USERNAME: 'backend'
  PASSWORD: 'rabbitmq_pass_backend_AC273677C1BF0364252283ECE8C70C25' 


SUPERVISOR:
  NAME: 'shoushou_video_golang'
  GROUPS:
    - NAME: 'shoushou_video_golang'
      PROGRAMS:
        - NAME: 'shoushou_video_golang-dist_command-ffmpeg'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/command -command=ffmpeg'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stderr.log'
        - NAME: 'shoushou_video_golang-dist_command-domain'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/command -command=domain'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-domain.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-domain.stderr.log'

        - NAME: 'shoushou_video_golang-dist_index'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/index -number=%(process_num)s'
          NUMPROCS: 8
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_index.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_index.stderr.log'




mysql_version: '5.6'      

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '192.168.1.2'       # 内网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost
            - '192.168.1.7'              # PHP       
          PASSWORD: 'mysql_pass_backend_81DB5D046334FBDB962D1E7DB38383B4'
          DATABASE: 'shoushou_video'
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 

            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend_CE2A3348D4FD9F8B6A22E96273FD8715'
          DATABASE: 'domain'



           


