--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'jiushiyumi.xyz zwmhyy.com.cn yecao07.me www.yecao07.me lives2-yc-test0708.xyz lives3-yec-sto07test.xyz'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'
      REWRITE: 1
      TRY_FILES: '$uri $uri/ /index.php?$query_string'


    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/'
      SERVER_NAME: 'www.yecaojule-07test.xyz yecaojule-07test.xyz'
      INDEX: 'www_index.html www_index.htm'
      M_SERVER_NAME: 'm.yecaojule-07test.xyz'
      REWRITE: 0
      TRY_FILES: '$uri $uri/ /www_index.html?$query_string'

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_koa/'
      SERVER_NAME: 'api.yecaojule-07test.xyz'
      INDEX: 'index.htm'
      REWRITE: 0
      PROXY_PORT: '4003'
      # WWW_SERVER_NAME: 'www.fea.yecaojule-07test.xyz'

      # WWW_SERVER_NAME: 'www.fea.yecaojule-07test.xyz'

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/'
      SERVER_NAME: 'm.yecaojule-07test.xyz'
      INDEX: 'm_index.html m_index.htm'
      REWRITE: 0
      # M_SERVER_NAME: 'm.fea.yecaojule-07test.xyz'
      WWW_SERVER_NAME: 'www.yecaojule-07test.xyz'
      TRY_FILES: '$uri $uri/ /m_index.html?$query_string'

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_domain_react/dist'
      SERVER_NAME: 'admin.ycdis-test.xyz'
      INDEX: 'index.html index.htm'
      REWRITE: 0
      TRY_FILES: '$uri $uri/ /index.html?$query_string'
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_golang-domain/dist'
      SERVER_NAME: 'api.ycdis-test.xyz'
      INDEX: 'index.html index.htm'
      PROXY_PORT: '4001'
      REWRITE: 0
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_domain_socketio/dist'
      SERVER_NAME: 'socket.ycdis-test.xyz'
      INDEX: 'index.html index.htm'
      PROXY_PORT: '4002'
      REWRITE: 0

RABBITMQ:
  VHOST: 'shoushou_video'
  USERNAME: 'backend'
  PASSWORD: 'rabbitmq_pass_backend'

SUPERVISOR:
  NAME: 'shoushou_video_golang'
  GROUPS:
    - NAME: 'shoushou_video_golang'
      PROGRAMS:
        - NAME: 'shoushou_video_golang-dist_command-ffmpeg'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/command -command=ffmpeg'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stderr.log'
        - NAME: 'shoushou_video_golang-dist_command-domain'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/command -command=domain'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-domain.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-domain.stderr.log'


        - NAME: 'shoushou_video_golang-dist_index'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/index'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_index.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_index.stderr.log'




mysql_version: '5.6'      

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '47.242.59.96'       # 外网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:

        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          DATABASE: 'shoushou_video'
          PASSWORD: 'mysql_pass_backend'
        - drop_user: false                 # index = 5
          with_grant_option: false
          GRANTS: 

            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend'
          DATABASE: 'domain'
        - drop_user: false                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'DELETE'
            - 'EXECUTE'
            - 'INSERT'
            - 'SELECT'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                
            - '47.242.59.96'
          PASSWORD: 'mysql_pass_qa'
          DATABASE: '*'