--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'fea.lives2-yc-test0708.xyz www.fea.lives2-yc-test0708.xyz fea.lives3-yec-sto07test.xyz www.fea.lives3-yec-sto07test.xyz'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'
      REWRITE: 1

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/'
      SERVER_NAME: 'www.fea.yecaojule-07test.xyz yecaojule-07test.xyz'
      INDEX: 'www_index.html www_index.htm'
      M_SERVER_NAME: 'm.fea.yecaojule-07test.xyz'
      REWRITE: 0
      # WWW_SERVER_NAME: 'www.fea.yecaojule-07test.xyz'

    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_download_js/'
      SERVER_NAME: 'm.fea.yecaojule-07test.xyz'
      INDEX: 'm_index.html m_index.htm'
      # M_SERVER_NAME: 'm.fea.yecaojule-07test.xyz'
      WWW_SERVER_NAME: 'www.fea.yecaojule-07test.xyz'
      REWRITE: 0

RABBITMQ:
  VHOST: 'shoushou_video'
  USERNAME: 'backend'
  PASSWORD: 'rabbitmq_pass_backend'

SUPERVISOR:
  NAME: 'shoushou_video_golang'
  GROUPS:
    - NAME: 'shoushou_video_golang'
      PROGRAMS:
        - NAME: 'shoushou_video_golang-dist_command-ffmpeg'
          DIRECTORY: '/var/www/shoushou_video_golang'
          COMMAND: '/var/www/shoushou_video_golang/dist/command -command=ffmpeg'
          NUMPROCS: 1
          STDOUT_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stdout.log'
          STDERR_LOGFILE: '/var/www/shoushou_video_golang/.log/shoushou_video_golang-dist_command-ffmpeg.stderr.log'


mysql_version: '5.6'      
MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '127.0.0.1'       # 内网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 

            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend'
          DATABASE: 'shoushou_video'
        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS:
            - 'DELETE'
            - 'EXECUTE'
            - 'INSERT'
            - 'SELECT'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_qa'
          DATABASE: 'shoushou_video'
    # - HOST: '10.0.0.181'       # 内网 IP   
    #   ENGINE: 'InnoDB'
    #   CONNECTIONS:
    #     - drop_user: true                 # index = 5
    #       with_grant_option: false
    #       GRANTS: 

    #         - 'ALTER ROUTINE'
    #         - 'CREATE'
    #         - 'CREATE ROUTINE'
    #         - 'CREATE TEMPORARY TABLES'
    #         - 'CREATE VIEW'
    #         - 'DELETE'
    #         - 'EVENT'
    #         - 'EXECUTE'
    #         - 'INSERT'
    #         - 'LOCK TABLES'
    #         - 'REFERENCES'
    #         - 'SELECT'
    #         - 'TRIGGER'
    #         - 'UPDATE'
    #       USER: 'backend'
    #       HOSTS: 
    #         - 'localhost'
    #         - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
    #       PASSWORD: 'mysql_pass_backend'
    #       DATABASE: 'shoushou_video'
    #     - drop_user: true                 # index = 5
    #       with_grant_option: false
    #       GRANTS: 

    #         - 'DELETE'
    #         - 'EXECUTE'
    #         - 'INSERT'
    #         - 'SELECT'
    #         - 'UPDATE'
    #       USER: 'backend'
    #       HOSTS: 
    #         - 'localhost'
    #         - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
    #       PASSWORD: 'mysql_pass_qa'
    #       DATABASE: 'shoushou_video'



           


