--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: 'fea.hdalvik.club www.fea.hdalvik.club'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'