--- # 优先次序高
NGINX:
  VHOSTS:
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_video_php'
      SERVER_NAME: '99percent.xyz jiushiyumi.xyz zwmhyy.com.cn yecao07.me www.yecao07.me lives2-yc-test0708.xyz lives3-yec-sto07test.xyz'
      INDEX: 'index.php index.html index.htm'
      PHP: '7.3'
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_dowanload_js/'
      SERVER_NAME: 'www.yecaojule-07test.xyz'
      INDEX: 'www_index.html www_index.htm'
    - HTTP_PORT: 80
      ROOT: '/var/www/shoushou_dowanload_js/'
      SERVER_NAME: 'm.yecaojule-07test.xyz'
      INDEX: 'm_index.html m_index.htm'


mysql_version: '5.6'      

MYSQL:
  GTID_MODE: yes
  TRANSACTION_ISOLATION: 'READ-COMMITTED'
  CHARACTER_SET: 'utf8mb4'
  COLLATION: 'utf8mb4_unicode_ci'
  SERVERS:
    - HOST: '47.242.59.96'       # 外网 IP   
      ENGINE: 'InnoDB'
      CONNECTIONS:

        - drop_user: true                 # index = 5
          with_grant_option: false
          GRANTS: 
            - 'ALTER ROUTINE'
            - 'CREATE'
            - 'CREATE ROUTINE'
            - 'CREATE TEMPORARY TABLES'
            - 'CREATE VIEW'
            - 'DELETE'
            - 'EVENT'
            - 'EXECUTE'
            - 'INSERT'
            - 'LOCK TABLES'
            - 'REFERENCES'
            - 'SELECT'
            - 'TRIGGER'
            - 'UPDATE'
          USER: 'backend'
          HOSTS: 
            - 'localhost'
            - '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost       
          PASSWORD: 'mysql_pass_backend'
          DATABASE: 'shoushou_video'