---
# supervisord 指的是 supervisord 守护进程 管理器
# supervisor  指的是 被管理的那些 php, python 等 进程
SUPERVISOR:
  FILE: '/var/run/supervisord/supervisord.sock'
  PIDFILE: '/var/run/supervisord/supervisord.pid'
  PORT: '*:9001'
  LOGFILE: '/var/log/supervisord/supervisord.log'
  SERVERURL: 'unix:///var/run/supervisord/supervisord.sock'
  FILES: '/etc/supervisor/conf.d/*.conf'
  USERNAME: 'backend'
  PASSWORD: 'supervisor_pass'
  PIDID: 'var/lib/supervisord/supervisord.pid'

