- name: (file) rm -Rf /var/lib/zookeeper
  file:
    path: /var/log/zookeeper
    state: absent
    
- name: (file) mkdir /var/lib/zookeeper
  file:
    path: /var/lib/zookeeper
    state: directory
    recurse: yes
    owner: zookeeper
    group: zookeeper
    mode: 0775