---
- name: (yum) yum remove mariadb-libs mysql-community* mysql-cluster-community*
  yum: 
    name: 
      - mariadb-libs
      - mysql-cluster-community*
      - mysql-community*
    state: absent
  
- name: "(file) rm -Rf {{ MYSQL.SERVERS[groups['cluster_mysql'].index(inventory_hostname)].DATADIR }}"
  file:
    state: absent
    path: "{{ MYSQL.SERVERS[groups['cluster_mysql'].index(inventory_hostname)].DATADIR }}"
    
- name: "(file) rm -Rf {{ MYSQL.SERVERS[groups['cluster_mysql'].index(inventory_hostname)].LOGDIR }}"
  file:
    state: absent
    path: "{{ MYSQL.SERVERS[groups['cluster_mysql'].index(inventory_hostname)].LOGDIR }}"
  
- name: (yum) yum insatll epel-release-latest-7.noarch.rpm
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    allow_downgrade: True
  
- name: (yum) yum insatll mysql-cluster-community-common-7.6.9-1.el7.x86_64.rpm
  yum: 
    name: https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.6/mysql-cluster-community-common-7.6.9-1.el7.x86_64.rpm
    allow_downgrade: True
  
- name: (yum) yum insatll mysql-cluster-community-libs-7.6.9-1.el7.x86_64.rpm
  yum: 
    name: https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.6/mysql-cluster-community-libs-7.6.9-1.el7.x86_64.rpm
    allow_downgrade: True
  
- name: (yum) yum insatll mysql-cluster-community-client-7.6.9-1.el7.x86_64.rpm
  yum: 
    name: https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.6/mysql-cluster-community-client-7.6.9-1.el7.x86_64.rpm
    allow_downgrade: True

- name: (yum) yum insatll mysql-cluster-community-server-7.6.9-1.el7.x86_64.rpm
  yum: 
    name: https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.6/mysql-cluster-community-server-7.6.9-1.el7.x86_64.rpm
    allow_downgrade: True
  notify: debug yum install cluster mysql

 
  