---
- name: (template) scp etc/nginx/vhosts/default.conf.j2 /etc/nginx/vhosts/*.conf
  template:
    src: etc/nginx/vhosts/default.conf.j2
    dest: "/etc/nginx/vhosts/{{ CONF['SERVER_NAME'] }}.conf"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ LOTTERY.NGINX.CONFS }}"
  loop_control:
    loop_var: CONF
  when: lottery_nginx is not undefined and lottery_nginx in ['yes', '1', 1, true, True, 'true', 'True', 'nginx']

- name: (service) service nginx restarted
  service:
    name: nginx
    state: restarted
  when: lottery_nginx is not undefined and lottery_nginx in ['yes', '1', 1, true, True, 'true', 'True', 'nginx']
