---
- name: (template) scp etc/supervisord.d/default.ini.j2 /etc/supervisord.d/*.ini
  template:
    src: etc/supervisord.d/default.ini.j2
    dest: "/etc/supervisord.d/lottery.ini"
    owner: root
    group: root
    mode: 0776
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ LOTTERY.SUPERVISOR.CONFS }}"
  loop_control:
    loop_var: CONF

  # notify: start nginx
