---

- name: (file) mkdir /etc/nginx/conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: "(file) rm -Rf /etc/nginx/conf.d/*.conf"
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob: '/etc/nginx/conf.d/*.conf'
  
  
- name: (file) mkdir /etc/nginx/vhosts
  file:
    path: /etc/nginx/vhosts
    state: directory
    mode: 0755

- name: (file) mkdir /etc/nginx/frameworks
  file:
    path: /etc/nginx/frameworks
    state: directory
    mode: 0755

- name: (template) scp etc/nginx/frameworks/*.conf /etc/nginx/frameworks/*.conf
  template:
    src: "{{ item }}"
    dest: /etc/nginx/frameworks/{{ item | basename }}
    mode: 0755
  with_fileglob: "./etc/nginx/frameworks/*.conf"
  # 读取的 是 files 目录下


- name: (template) scp etc/nginx/conf.d/*.conf /etc/nginx/conf.d/*.conf
  template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item | basename }}
    mode: 0644
  with_fileglob: "./etc/nginx/conf.d/*.conf"
  # 读取的 是 files 目录下

- name: (template) scp etc/nginx/mime.types.j2 /etc/nginx/mime.types
  template:
    src: etc/nginx/mime.types.j2
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: 0644
    backup: no

- name: (template) scp etc/nginx/nginx.conf.j2 /etc/nginx/nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: no
  # 读取的 是 templates 目录下

