---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
- name: (yum) yum remove nginx
  yum:
    name: nginx
    state: absent    
- name: (yum) yum install nginx
  yum:
    name: nginx
    state: present