---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
- name: (yum) yum remove nginx
  yum:
    name: nginx
    state: absent    
- name: (yum) yum install nginx
  yum:
    name: nginx
    state: present




- name: (get_url) wget http://nginx.org/download/nginx-{{ NGINX.VERSION | default('1.18.0') }}.tar.gz
  get_url:
    url: "http://nginx.org/download/nginx-{{ NGINX.VERSION | default('1.18.0') }}.tar.gz"
    dest: "/tmp/nginx-{{ NGINX.VERSION | default('1.18.0') }}.tar.gz"
    mode: 0775
  # notify: 
  #   - debug yum install nginx

# notify 是 ansible 状态 为 changed 才执行， 
# 在所有 tasks 完成后执行， 
# 次序是 roles/*/handlers 内的次序 不是 notifiy 的次序