---
- name: (yum) yum remove percona-xtrabackup*
  yum:
    name: percona-xtrabackup*
    state: absent
- name: (yum) yum https://www.percona.com/downloads/Percona-XtraBackup-LATEST/Percona-XtraBackup-8.0.14/binary/redhat/7/x86_64/percona-xtrabackup-80-debuginfo-8.0.14-1.el7.x86_64.rpm
  yum: # 请去 ELK 官网 找最新 rpm
    name: https://www.percona.com/downloads/Percona-XtraBackup-LATEST/Percona-XtraBackup-8.0.14/binary/redhat/7/x86_64/percona-xtrabackup-80-debuginfo-8.0.14-1.el7.x86_64.rpm
    state: present
  when: xtrabackup_version == '8.0'  # 对于 MySQL 8.0 友好
- name: (yum) yum install https://www.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.20/binary/redhat/7/x86_64/percona-xtrabackup-24-2.4.20-1.el7.x86_64.rpm
  yum: # 请去 ELK 官网 找最新 rpm
    name: https://www.percona.com/downloads/Percona-XtraBackup-2.4/Percona-XtraBackup-2.4.20/binary/redhat/7/x86_64/percona-xtrabackup-24-2.4.20-1.el7.x86_64.rpm
    state: present
  when: xtrabackup_version == '2.4' # 对于 MySQL 5.6  5.7 友好