- name: (file) rm -Rf /var/lib/kafka
  file:
    path: /var/log/kafka
    state: absent
    
- name: (file) mkdir /var/lib/kafka
  file:
    path: /var/lib/kafka
    state: directory
    # recurse: yes
    owner: kafka
    group: kafka
    mode: 0775