- name: (file) rm -Rf /var/log/kafka
  file:
    path: /var/log/kafka
    state: absent
    
- name: (file) mkdir /var/log/kafka
  file:
    path: '/var/log/kafka'
    state: 'directory'
    owner: kafka
    group: kafka
    mode: '0775'