---
- name: (service) service kafka stop
  service:
    name: kafka
    state: stopped
  ignore_errors: yes


- name: (get_url) wget https://downloads.apache.org/kafka/2.6.0/kafka_2.12-2.6.0.tgz
  get_url:
    url: "https://downloads.apache.org/kafka/2.6.0/kafka_2.12-2.6.0.tgz"
    dest: "/tmp/kafka_2.12-2.6.0.tgz"
    mode: 0775

- name: (file) rm -Rf /opt/kafka
  file:
    path: /opt/kafka
    state: absent

- name: (file) mkdir /opt/kafka
  file:
    path: /opt/kafka
    state: directory
    owner: kafka
    group: kafka
    mode: 0775
    recurse: yes

- name: (unarchive) tar zxvf /tmp/kafka_2.12-2.6.0.tgz
  unarchive:
    src: "/tmp/kafka_2.12-2.6.0.tgz"
    dest: /opt/kafka
    extra_opts: [--strip-components=1]

- name: (file) chown -r kafka:kafka /opt/kafka
  file:
    path: /opt/kafka
    state: directory
    recurse: yes
    owner: kafka
    group: kafka
    mode: 0755