---

- name: (systemd) systemctl daemon-reload
  systemd:
    name: kafka
    state: reloaded

- name: (service) service kafka restarted
  service:
    name: kafka
    state: restarted
# - name: Debug start nginx
#   debug: 
#     msg: 'The key value is !!'
#   when: debug==true or debug==1
    