---

- name: (yum) yum insatll ius-release.rpm
  yum: 
    name: https://centos7.iuscommunity.org/ius-release.rpm
    
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
- name: (yum) yum remove python-pip python
  yum:
    name: python-pip
    state: absent

- name: (yum) yum install python
  yum: 
    name:
      - python-pip
    state: latest
  when: python_version == '2.7'

- name: "(yum) yum install python{{ python_version | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}u python{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}u-devel"
  yum: 
    name:
      - "python{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}u-pip"
    state: latest
  when: python_version == '3.4' or  python_version == '3.5' or  python_version == '3.6'
  
- name: "(file) ln -sf /usr/local/bin/pip{{ python_version | default(3.6) }} /usr/bin/pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }}"  
  file:
    src: "/usr/local/bin/pip{{ python_version | default(3.6) }}"
    dest: "/usr/bin/pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }}"
    state: link
    force: True
    follow: False

- name: "(shell) pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} install --upgrade pip"
  shell: "pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} install --upgrade pip"