---

- name: "(command) rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  command: "rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  ignore_errors: yes

- name: "(command) rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  command: "rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  ignore_errors: yes


- name: rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*' '.*' '.*'
  command: rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*' '.*' '.*'
  ignore_errors: yes


- name: rabbitmqctl set_user_tags '{{ RABBITMQ.USERNAME }}' administrator
  command: rabbitmqctl set_user_tags '{{ RABBITMQ.USERNAME }}' administrator
  ignore_errors: yes

# enbable rabbitmq web mangement 之後 API 才會生效
- name: rabbitmq-plugins enable rabbitmq_management
  command: rabbitmq-plugins enable rabbitmq_management
  ignore_errors: yes
