---

- name: "(command) rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  command: "rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  ignore_errors: yes

- name: "(command) rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  command: "rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  ignore_errors: yes


- name: rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*'' '.*'' '.*'
  command: rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*' '.*' '.*'
  ignore_errors: yes


- name: rabbitmqctl set_user_tags -p '{{ RABBITMQ.USERNAME }}' administrator
  command: rabbitmqctl set_user_tags -p '{{ RABBITMQ.USERNAME }}' administrator
  ignore_errors: yes
