---

- name: "(shell) pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  shell: "pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  register: s_pip_version

- name: debug s_pip_version
  debug: 
    msg: "{{ s_pip_version }}"