---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: latest

    
- name: (yum) yum install https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
  yum: 
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm

- name: (yum) yum ffmpeg ffmpeg-devel
  yum:
    name: ffmpeg ffmpeg-devel
    state: latest

