- import_tasks: yum-install-supervisor.yml
- import_tasks: template-etc-supervisor-supervisord_conf.yml
- import_tasks: template-lib_systemd_system_supervisord_service.yml
- import_tasks: service-supervisord-restart.yml
