---

- name: (file) mkdir /etc/supervisord
  file:
    path: /etc/supervisord
    state: directory
    mode: 0755

- name: (template) scp etc/supervisor/supervisord.conf.j2 /etc/supervisord/supervisord.conf
  template:
    src: etc/supervisor/supervisord.conf.j2
    dest: /etc/supervisord/supervisord.conf
    owner: root
    group: root
    mode: 0776
    backup: no

- name: (file) mkdir /etc/supervisord/supervisord.d
  file:
    path: /etc/supervisord/supervisord.d
    state: directory
    mode: 0755
   #读取的 是 templates 目录下

