---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
- name: (yum) yum remove supervisor
  yum:
    name: supervisor
    state: absent    
- name: (yum) yum install supervisor
  yum:
    name: supervisor
    state: present