---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: (template) scp tmp/mgr-3.sql.j2 /tmp/mgr-3.sql
  template:
    src: tmp/mgr-3.sql.j2
    dest: /tmp/mgr-3.sql
    owner: mysql
    group: mysql
    mode: 0777
- name: (shell) mysql --force < /tmp/mgr-3.sql
  shell: mysql --force < /tmp/mgr-3.sql
  when: mysql_ha == 'mgr-multiple'
  
