---

- name: (yum) yum remove mysql* mysql-community* mysql-cluster-community* percona-server-server
  yum: 
    name:
      - mysql*
      - mysql-cluster-community*
      - mysql-community*
      - Percona-XtraDB-Cluster
    state: absent
  
- name: (yum) yum insatll Percona-XtraDB-Cluster rpm
  yum: 
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    allow_downgrade: True

- name: "(command) sudo percona-release setup ps80"
  command: "percona-release setup ps{{ mysql_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}"


- name: (yum) yum install percona-server-server
  yum: 
    name:
      -  percona-server-server
    state: latest
    
    
