---
- name: (yum) yum remove git*
  yum: 
    name: git*
    state: absent
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present

- name: (yum) yum insatll https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
  yum: 
    name: https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
- name: (yum) yum install git
  yum:
    name: git
  # notify: debug yum install git