---
- name: (yum_repository) bintray--sobolevn-rpm.repo
  yum_repository:
    name: bintray--sobolevn-rpm.repo
    description: bintray--sobolevn-rpm
    file: bintray--sobolevn-rpm
    baseurl: https://dl.bintray.com/sobolevn/rpm
    gpgcheck: no
    repo_gpgcheck: 0
    enabled: 1

- name: (yum) yum install git-secret
  yum:
    name: git-secret
  # notify: debug yum install git