---
- name: node -v
  shell: node -v
  register: s_node_version
  become: False
- name: debug s_node_version
  debug: 
    msg: "{{ s_node_version }}"
- name: npm -v
  shell: npm -v
  register: s_npm_version
  become: False
- name: debug s_npm_version
  debug: 
    msg: "{{ s_npm_version }}"