---
- name: "(git) git clone git@gitlab.com:dalvik009/shoushou_video_php.git /var/www/shoushou_video_php"
  git:
    repo: 'git@gitlab.com:dalvik009/shoushou_video_php.git'
    dest: "/var/www/shoushou_video_php"
    version: "{{ 'develop' if branch is not defined or branch in ['fea', 'feature'] else branch }}"
    # version: "{{ 'master' }}"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  ignore_errors: True # Because this shell will not response, that ansible will determine it as error
  when: git is not undefined and git in ['yes', '1', 1, true, True, 'true', 'True', 'git']

  
# - name: (template) scp var/www/lottery-service_resource_backend-lumen/.env.j2 /var/www/lottery-service_resource_backend-lumen/.env
#   template:
#     src: var/www/lottery-service_resource_backend-lumen/.env.j2
#     dest: /var/www/lottery-service_resource_backend-lumen/.env
#     owner: root
#     group: root
#     mode: 0776
#     backup: no   
