---
- name: "(git) git clone git@gitlab.com:dalvik009/shoushou_video_php.git /var/www/shoushou_video_php"
  git:
    repo: 'git@gitlab.com:dalvik009/shoushou_video_php.git'
    dest: "/var/www/shoushou_video_php"
    version: "{{ 'develop' if branch is not defined or branch in ['fea', 'feature', 'dev', 'develop'] else 'release' if branch in ['rel', 'release'] else 'master' if branch in ['mas', 'master'] else 'develop'}}"
    # version: "{{ 'master' }}"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone
  when: git is not undefined and git == 1

- name: 'chmod -R 777 /var/www/shoushou_video_php'
  file:
    path: /var/www/shoushou_video_php
    owner: root
    group: root
    recurse: yes
    mode: '0777'
  when: git is not undefined and git == 1
  
