---


- name: (template) scp tmp/shoushou_video.sql.j2 /tmp/shoushou_video.sql
  template:
    src: tmp/shoushou_video.sql.j2
    dest: /tmp/shoushou_video.sql
    owner: root
    group: root
    mode: 0776
    backup: no
  when: mysql is not undefined and mysql == 1



- name: (shell) mysql < /tmp/shoushou_video.sql
  shell: mysql < /tmp/shoushou_video.sql
  when: mysql is not undefined and mysql == 1



- name: (template) scp tmp/domain.sql.j2 /tmp/domain.sql
  template:
    src: tmp/domain.sql.j2
    dest: /tmp/domain.sql
    owner: root
    group: root
    mode: 0776
    backup: no
  when: mysql is not undefined and mysql == 1



- name: (shell) mysql < /tmp/domain.sql
  shell: mysql < /tmp/domain.sql
  when: mysql is not undefined and mysql == 1


- name: (template) scp tmp/grant.sql.j2 /tmp/grant.sql
  template:
    src: tmp/grant.sql.j2
    dest: /tmp/grant.sql
    owner: root
    group: root
    mode: 0755
  when: mysql is not undefined and mysql == 1


    
- name: "(shell) mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
  shell: "mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
  when: mysql is not undefined and mysql == 1

  
