---


- name: (template) scp tmp/shoushou_video.sql.j2 /tmp/shoushou_video.sql
  template:
    src: tmp/shoushou_video.sql.j2
    dest: /tmp/shoushou_video.sql
    owner: root
    group: root
    mode: 0776
    backup: no
  tags:
  - mysql


- name: (shell) mysql < /tmp/shoushou_video.sql
  shell: mysql < /tmp/shoushou_video.sql
  tags:
  - mysql


- name: (template) scp tmp/grant.sql.j2 /tmp/grant.sql
  template:
    src: tmp/grant.sql.j2
    dest: /tmp/grant.sql
    owner: root
    group: root
    mode: 0755
  tags:
  - mysql

    
- name: "(shell) mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
  shell: "mysql --user='root' --password='mysql_pass_cli' --force < /tmp/grant.sql"
  tags:
  - mysql
  
