---
- name: (shell) date +%Y-%m-%d%H-%M-%S.%5N
  shell: "date +%Y-%m-%d_%H-%M-%S.%5N"
  register: o_date
  when: (nginx is not undefined and nginx == 1)

- name: "(file) mkdir /etc/nginx/vhost-{{ o_date.stdout }}"
  file:
    path: "/etc/nginx/vhosts-{{ o_date.stdout }}"
    force: yes
    state: directory
  when: (nginx is not undefined and nginx == 1)

- name: "(template) cp -Rf /etc/nginx/vhosts/* /etc/nginx/vhosts-{{ o_date.stdout }}/"
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/vhosts-{{ o_date.stdout }}/"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_lines: "find /etc/nginx/vhosts -type f -name '*.conf'"
  when: (nginx is not undefined and nginx == 1)

- name: "(template) scp etc/nginx/vhosts/default.conf.j2 /etc/nginx/vhosts/*.conf  nginx={{ nginx }}  ,nginx_restart={{ nginx_restart }}"
  template:
    src: etc/nginx/vhosts/default.conf.j2
    dest: "/etc/nginx/vhosts/{{ VHOST['SERVER_NAME'] | replace(' ', '_') }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ NGINX.VHOSTS }}"
  loop_control:
    loop_var: VHOST
  when: (nginx is not undefined and nginx == 1) 


  
- name: (service) service nginx restarted
  service:
    name: nginx
    state: restarted
  when: (nginx is not undefined and nginx == 1) and (nginx_restart is not undefined and nginx_restart == '1')
