---
- name: (template) scp etc/nginx/vhosts/default.conf.j2 /etc/nginx/vhosts/*.conf
  template:
    src: etc/nginx/vhosts/default.conf.j2
    dest: "/etc/nginx/vhosts/{{ VHOST['SERVER_NAME'] | replace(' ', '_') }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: no
    #validate: nginx -t -c /etc/nginx/nginx.conf
  with_items: "{{ NGINX.VHOSTS }}"
  loop_control:
    loop_var: VHOST
  when: (nginx is not undefined and nginx == 1) 


  
- name: (service) service nginx restarted == 1
  service:
    name: nginx
    state: restarted
  when: (nginx is not undefined and nginx == 1) and (nginx_restart is not undefined and nginx_restart == 1)
