---

- name: "(command) rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  command: "rabbitmqctl add_user '{{ RABBITMQ.USERNAME }}' '{{ RABBITMQ.PASSWORD }}'"
  when: rabbitmq is not undefined and rabbitmq == 1  
  ignore_errors: yes

- name: "(command) rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  command: "rabbitmqctl add_vhost '{{ RABBITMQ.VHOST }}'"
  when: rabbitmq is not undefined and rabbitmq == 1
  ignore_errors: yes


- name: (command) rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*' '.*' '.*'
  command: rabbitmqctl set_permissions -p '{{ RABBITMQ.VHOST }}' '{{ RABBITMQ.USERNAME }}' '.*' '.*' '.*'
  when: rabbitmq is not undefined and rabbitmq == 1
  ignore_errors: yes
