---
- name: "(shell) sudo masterha_check_repl --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_repl --conf={{ MASTERHA.CONF }}"
  register: s_masterha_repl
  ignore_errors: yes
- name: (debug) s_masterha_repl
  debug: 
    msg: "{{ s_masterha_repl }}"