---

# - name: "(command) npm global remove pm2"
#   command: "yarn global remove pm2"
- name: "(command) yarn global add pm2"
  command: "yarn global add pm2"
  # notify: 

  # notify: 
  #   - debug yum install nodejs