---

# - name: "(command) npm global remove pm2"
#   command: "yarn global remove pm2"
- name: "(command) yarn global add pm2"
  command: "yarn global add pm2"
- name: "(command) pm2 install pm2-logrotate"
  command: "pm2 install pm2-logrotate"
  become: false

- name: "(command) pm2 set pm2-logrotate:max_size 10MB"
  command: "pm2 set pm2-logrotate:max_size 10MB"
  become: false
- name: "(command) pm2 set pm2-logrotate:compress true"
  command: "pm2 set pm2-logrotate:compress true"
  become: false
- name: "(command) pm2 set pm2-logrotate:retain 200"
  command: "pm2 set pm2-logrotate:retain 200"
  become: false
  # notify: 

  # notify: 
  #   - debug yum install nodejs