---
# - name: (systemd) systemd elasticsearch restarted
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: elasticsearch
- name: (service) service elasticsearch started
  service:
    name: elasticsearch
    state: started
    enabled: yes
 
    
# 这里有个坑 
# 一定要 service elasticsearch start 两次
# 第二次 service elasticsearch start 无法用 ansible 模组
- name: (shell) service elasticsearch start
  shell: service elasticsearch start
  
- name: (shell) service elasticsearch status
  shell: service elasticsearch status
  notify: debug yum install elasticsearch
 
 # 这里有个坑 
 # 需要等待一段时间 service 才会起来
- name: (pause) sleep 1m
  pause:
    minutes: 1
    
- name: "(uri) curl {{ELASTICSEARCH.NETWORK_HOST}}:{{ELASTICSEARCH.HTTP_PORT}}"
  uri:
    url: "http://{{ELASTICSEARCH.NETWORK_HOST}}:{{ELASTICSEARCH.HTTP_PORT}}"
    method: GET
    return_content: yes
    status_code: 200
  register: s_elasticsearch_version

