---
- name: (yum) yum remove elasticsearch*
  yum:
    name: elasticsearch*
    state: absent
- name: (yum) yum install elasticsearch-{{ elasticsearch_version | default(6.4.2) }}.rpm
  yum: # 请去 ELK 官网 找最新 rpm
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version | default(6.4.2) }}.rpm
    state: present