---
- name: "(git) git clone git@gitlab.ques98.cn:lottery/lottery-crawler_all_backend-scrapy.git /var/www/lottery-crawler_all_backend-scrapy"
  git:
    repo: 'git@gitlab.ques98.cn:lottery/lottery-crawler_all_backend-scrapy.git'
    dest: "/var/www/lottery-crawler_all_backend-scrapy"
    version: "{{ 'develop' if branch is not defined or branch in ['fea', 'feature'] else branch }}"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  become: no # 使用 vagrant:vagrant git clone 下来， 不使用 root git clone

- name: (shell) pip3 install -r requirement.txt
  shell: pip3 install -r requirement.txt
  args:
    chdir: "/var/www/lottery-crawler_all_backend-scrapy"
  register: s_pip3_install
  
  
- name: (template) scp var/www/lottery-crawler_all_backend-scrapy/.env.j2 /var/www/lottery-crawler_all_backend-scrapy/.env
  template:
    src: var/www/lottery-crawler_all_backend-scrapy/.env.j2
    dest: /var/www/lottery-crawler_all_backend-scrapy/.env
    owner: root
    group: root
    mode: 0776
    backup: no  
  
      
- name: (file) mkdir /var/run/supervisord
  file:
    path: /var/run/supervisord
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0777
    
- name: (shell) supervisorctl -c /etc/supervisor/supervisor.conf
  shell: supervisorctl -c /etc/supervisor/supervisor.conf
    
- name: '(shell) supervisorctl restart lottery-crawler_all_backend-scrapy:'
  shell: 'supervisorctl restart lottery-crawler_all_backend-scrapy:'


# chmod -R 700 /root/.ssh/id_rsa
# chmod -R 700 /root/.ssh/id_rsa.pub
# key must be put in root because sudo git clone
# sudo supervisorctl -c /etc/supervisor/supervisor.conf
