---
- name: "(service) service php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-fpm restarted"
  service:
    name: "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-fpm"
    state: restarted