---
- name: "(template) scp etc/opt/remi/php/php-fpm.d/www.conf.j2 /etc/opt/remi/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}/php-fpm.d/www.conf"
  template:
    src: etc/opt/remi/php/php-fpm.d/www.conf.j2
    dest: "/opt/remi/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}/root/etc/php-fpm.d/www.conf"
    owner: root
    group: root
    mode: 0766
  when: php_version == '5.3' or php_version == '5.4' or php_version == '5.5' or php_version == '5.6'
  # 没有 php53
- name: "(template) scp etc/opt/remi/php/php-fpm.d/www.conf.j2 /etc/opt/remi/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}/php-fpm.d/www.conf"
  template:
    src: etc/opt/remi/php/php-fpm.d/www.conf.j2
    dest: "/etc/opt/remi/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}/php-fpm.d/www.conf"
    owner: root
    group: root
    mode: 0766
  when: php_version == '7.0' or php_version == '7.1' or php_version == '7.2' or php_version == '7.3'