---
- name: (yum) yum insatll epel-release-latest-7.noarch.rpm
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
- name: (yum) yum insatll remi.rpm
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: "(yum) yum remove php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}..."
  yum: 
    name: "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}"
    state: absent

- name: "(yum) yum install php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}..."
  yum: 
    name:
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}"
    
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-memcached"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-pdo"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-pdo_mysql"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-mcrypt"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-cli"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-gd"
      # - php-curl 
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-mysql"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-ldap"
      # - php-zip 
      # - php-fileinfo
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-fpm"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-common" 
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-devel"
      # - php-pecl-json # php 5.6 没有
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-mbstring" 
      # - php-mysqlnd 
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-xml"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-xmlrpc" 
      # - php-opcache # php 5.6 没有
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-pecl-xdebug" # php 7.0 开始 可以 php-xdebug ， php 5.6 不可用 php-xdebug
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-swoole"
      - "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}-php-zip"
    state: latest
  #notify: debug yum install php
  
- name: "(file) ln -sf /usr/bin/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }} /usr/bin/php"  
  file:
    src: "/usr/bin/php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}"
    dest: "/usr/bin/php"
    state: link
    force: True
    follow: False
- name: (group) groupadd nginx
  group:
    name: nginx
    state: present
- name: (user) adduer nginx
  user:
    name: nginx
    comment: nginx
    uid: 1001
    group: nginx
  ignore_errors: yes