---
- name: "(shell) sudo masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  shell: "masterha_check_ssh --conf={{ MASTERHA.CONF }}"
  register: s_masterha_ssh
  ignore_errors: yes
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups['masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
- name: (debug) s_masterha_ssh
  run_once: true
  debug: 
    msg: "{{ s_masterha_ssh }}"