---
- name: "(shell) sudo ndb_mgm -e 'show'"
  shell: "sudo ndb_mgm -e 'show'"
  register: s_ndb_show
  ignore_errors: yes
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups['ndb_mgm'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
- name: (debug) s_ndb_show
  run_once: true
  debug: 
    msg: "{{ s_ndb_show }}"
  