---
- name: Install feature beanstalkd
  hosts: fea-beanstalkd
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "本地 feature 环境，Beanstalkd 安装开始"
      shell: echo 'playbook beanstalkd starts'
  roles:
    - role: beanstalkd
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Beanstalkd 安装完毕"
      shell: echo 'playbook beanstalkd ends'
  vars:
- name: Install develop beanstalkd
  hosts: dev-beanstalkd
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "开发 develop 环境，Beanstalkd 安装开始"
      shell: echo 'playbook beanstalkd starts'
  roles:
    - role: beanstalkd
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，Beanstalkd 安装完毕"
      shell: echo 'playbook beanstalkd ends'
