---
- name: Install beanstalkd
  hosts: beanstalkd
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: 嚴重警告!!!!!!!!!!!!!!!!!!!!
      pause:
        prompt: 確定 要在 master 環境下嗎? 後果自行負責!
      when: branch == 'mas'
    - name: "{{ branch }} 环境，Beanstalkd 安装开始"
      shell: echo 'playbook beanstalkd starts'
  roles:
    - role: beanstalkd
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Beanstalkd 安装完毕"
      shell: echo 'playbook beanstalkd ends'
  vars:

