---
- name: Install feature certbot
  hosts: fea-certbot
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "本地 feature 环境，Certbot 安装开始"
      shell: echo 'playbook certbot starts'
  roles:
    - role: certbot
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Certbot 安装开始"
      shell: echo 'playbook certbot ends'
  vars:
- name: Install develop certbot
  hosts: dev-certbot
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "开发 devlop 环境，Certbot 安装开始"
      shell: echo 'playbook certbot starts'
  roles:
    - role: certbot
      vars:
        bra: dev
      when: branch is defined and branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 devlop 环境，Certbot 安装完毕"
      shell: echo 'playbook certbot ends'


- name: Install release certbot
  hosts: rel-certbot
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "开发 release 环境，Certbot 安装开始"
      shell: echo 'playbook certbot starts'
  roles:
    - role: certbot
      vars:
        bra: rel
      when: branch is defined and branch in ['rel', 'release', 'all']
  post_tasks:
    - name: "开发 release 环境，Certbot 安装完毕"
      shell: echo 'playbook certbot ends'
