---
- name: Install feature chatroom-mongodb
  hosts: fea-chatroom-mongodb
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  vars_files:
    - ./../group_vars/chatroom.{{branch}}.yml
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "!!!!!!!!!!!!!!!!!!!!嚴重警告!!!!!!!!!!!!!!!!!!!!"
      pause:
        prompt: 確定 要在 master 環境下嗎? 後果自行負責!
      when: branch == 'mas'
    - name: "{{ branch }} certbot 安装开始"
      shell: echo 'playbook certbot starts'
  roles:
    - role: chatroom
      vars: 
        bra: fea
        chatroom_mongodb: true
  post_tasks:
    - name: "本地 feature 环境，chatroom-mongodb 安装开始"
      shell: echo 'playbook chatroom-mongodb ends'
   