---

- name: install cluster_mysql
  hosts: cluster_mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  vars_files:
    - ./../group_vars/chrome.{{ branch }}.yml
    - ./../group_vars/mysql.{{ branch }}.yml
    - ./../group_vars/masterha.{{ branch }}.yml
    - ./../group_vars/cluster_ndb.{{ branch }}.yml
    - ./../group_vars/cluster_ndb_mgm.{{ branch }}.yml
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "!!!!!!!!!!!!!!!!!!!!嚴重警告!!!!!!!!!!!!!!!!!!!!"
      pause:
        prompt: 確定 要在 master 環境下嗎? 後果自行負責!
      when: branch == 'mas'
    - name: "{{ branch }} 环境 cluster_mysql 安装开始"
      shell: echo 'playbook cluster_mysql starts'
  roles:
    - role: cluster_mysql
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Cluster MySQL 安装完毕"
      shell: echo 'playbook cluster_mysql ends'
    
    

####################

  