---

- name: install feature cluster_ndb_mgm
  hosts: fea-cluster_ndb_mgm
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.fea.yml
    - ./../group_vars/masterha.fea.yml
    - ./../group_vars/cluster_ndb.fea.yml
    - ./../group_vars/cluster_ndb_mgm.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Cluster NDB MGM 安装开始"
      shell: echo 'playbook cluster_ndb_mgm starts'
  roles:
    - role: pause
      vars:
        bra: fea
    - role: cluster_ndb_mgm
      vars:
        bra: fea
      when: (branch is not defined or branch in ['fea', 'feature', 'all'] )
  post_tasks:
    - name: "本地 feature 环境，Cluster NDB MGM 安装完毕"
      shell: echo 'playbook cluster_ndb_mgm ends'
    


####################

- name: install develop cluster_ndb_mgm
  hosts: dev-cluster_ndb_mgm
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.dev.yml
    - ./../group_vars/masterha.dev.yml
    - ./../group_vars/cluster_ndb.dev.yml
    - ./../group_vars/cluster_ndb_mgm.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，Cluster NDB MGM 安装开始"
      shell: echo 'playbook cluster_ndb_mgm starts'
  roles:
    - role: pause
      vars:
        bra: dev
    - role: cluster_ndb_mgm
      vars:
        bra: dev
      when: (branch is defined and branch in ['dev', 'develop', 'all'] )
  post_tasks:
    - name: "开发 develop 环境，Cluster NDB MGM 安装完毕"
      shell: echo 'playbook cluster_ndb_mgm ends'
    
      
      
###################################################



- name: install release cluster_ndb_mgm
  hosts: rel-cluster_ndb_mgm
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.rel.yml
    - ./../group_vars/masterha.rel.yml
    - ./../group_vars/cluster_ndb.rel.yml
    - ./../group_vars/cluster_ndb_mgm.rel.yml
  pre_tasks:
    - name: "开发 release 环境，Cluster NDB MGM 安装开始"
      shell: echo 'playbook cluster_ndb_mgm starts'
  roles:
    - role: pause
      vars:
        bra: rel
    - role: cluster_ndb_mgm
      vars:
        bra: rel
      when: (branch is defined and branch in ['rel', 'release', 'all'] )
  post_tasks:
    - name: "开发 release 环境，Cluster NDB MGM 安装完毕"
      shell: echo 'playbook cluster_ndb_mgm ends'
    