---

- name: install feature cluster_ndb
  hosts: fea-cluster_ndb
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.fea.yml
    - ./../group_vars/masterha.fea.yml
    - ./../group_vars/cluster_ndb.fea.yml
    - ./../group_vars/cluster_ndb_mgm.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Cluster NDB 安装开始"
      shell: echo 'playbook cluster_ndb starts'
  roles:
    - role: cluster_ndb
      vars:
        bra: fea
      when: (branch is not defined or branch in ['fea', 'feature' ,'all'] ) 
  post_tasks:
    - name: "本地 feature 环境，Cluster NDB 安装完毕"
      shell: echo 'playbook cluster_ndb ends'   
    
####################
