---
- name: Install feature elasticsearch
  hosts: fea-elasticsearch
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/elasticsearch.fea.yml
  pre_tasks:
    - shell: echo 'playbook elasticsearch starts'
  roles:
    - role: elasticsearch
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook elasticsearch ends'
  vars: