---
- name: Install elasticsearch
  hosts: elasticsearch
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: "[單選] 你要運行在那種模式下 fea, dev, rel, mas ?"
      private: no
  vars_files:
    - ./../group_vars/elasticsearch.{{ branch }}.yml
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
      pause:
        prompt: "[警告] 確定 要在 master 環境下嗎? 後果自行負責!"
      when: branch == 'mas'
    - name: "{{ branch }} elasticsearch 安装开始"
      shell: echo 'playbook elasticsearch starts'
  roles:
    - role: elasticsearch
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook elasticsearch ends'
  vars: