---
- name: Install erlang
  hosts: erlang
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/erlang.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Erlang 安装开始"
      shell: echo 'playbook Erlang starts'
  roles:
    - role: erlang
      vars: 
        bra: branch
  post_tasks:
    - name: "{{ branch }}  环境，Erlang 安装完毕"
      shell: echo 'playbook Erlang ends'
  vars:
