---
- name: Install feature erlang
  hosts: fea-erlang
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/erlang.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Erlang 安装开始"
      shell: echo 'playbook Erlang starts'
  roles:
    - role: erlang
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Erlang 安装完毕"
      shell: echo 'playbook Erlang ends'
  vars:
