---
- name: Install feature git
  hosts: fea-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook git starts'
  roles:
    - role: git
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook git ends'
  vars:
- name: Install develop git
  hosts: dev-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook git starts'
  roles:
    - role: git
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook git ends'

- name: Install master git
  hosts: mas-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook git starts'
  roles:
    - role: git
      vars:
        bra: mas
      when: branch == 'mas' or branch == 'master' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook git ends'
