---
- name: Install feature git
  hosts: git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook git starts'
  roles:
    - role: git
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook git ends'
  vars:
