---
- name: "Install feature golang"
  hosts: golang
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: "echo 'playbook golang starts' "
  roles:
    - role: golang
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook golang ends'
