---
- name: "Install feature golang"
  hosts: fea-golang
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: "echo 'playbook golang starts' "
  roles:
    - role: golang
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - shell: echo 'playbook golang ends'
