---
- name: Install feature java
  hosts: java
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook java starts'
  roles:
    - role: java
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook java ends'
  vars: