---
- name: Install feature java
  hosts: fea-java
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook java starts'
  roles:
    - role: java
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook java ends'
  vars:
- name: Install develop java
  hosts: dev-java
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook java starts'
  roles:
    - role: java
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook java ends'
# - name: Install release nginx
#   hosts: rel_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - rel
# - name: Install master nginx
#   hosts: mas_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - mas