---
- name: Install feature kibana
  hosts: kibana
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/kibana.fea.yml
  pre_tasks:
    - shell: echo 'playbook kibana starts'
  roles:
    - role: kibana
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook kibana ends'
