
---
- name: Install feature lottery-nginx
  hosts: fea-lottery-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，lottery-nginx 安装开始"
      shell: echo 'playbook lottery-nginx starts'
  roles:
    - role: lottery
      vars:
        bra: fea
        lottery_nginx: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，lottery 安装完毕"
      shell: echo 'playbook lottery ends'
      
- name: Install feature lottery-mysql
  hosts: fea-lottery-mysql
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，lottery-mysql 安装开始"
      shell: echo 'playbook lottery-mysql starts'
  roles:
    - role: lottery
      vars:
        bra: fea
        lottery_mysql: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，lottery-mysql 安装完毕"
      shell: echo 'playbook lottery-mysql ends'

- name: Install feature lottery-supervisor
  hosts: fea-lottery-supervisor
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，lottery-supervisor 安装开始"
      shell: echo 'playbook lottery-supervisor starts'
  roles:
    - role: lottery
      vars:
        bra: fea
        lottery_supervisor: true
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，lottery-mysql 安装完毕"
      shell: echo 'playbook lottery-mysql ends' 
      
      
- name: Install develop lottery
  hosts: dev-lottery
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/lottery.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，lottery 安装开始"
      shell: echo 'playbook lottery starts'
  roles:
    - role: lottery
      vars:
        bra: dev
      when: branch is defined and branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，lottery 安装完毕"
      shell: echo 'playbook lottery ends'