---
- name: Install feature memcached
  hosts: fea-memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook memcached ends'
  vars:
- name: Install develop memcached
  hosts: dev-memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook memcached ends'
