---
- name: Install feature memcached
  hosts: memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook memcached ends'
  vars: