---
- name: Install feature memcached
  hosts: fea-memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: fea
      when: branch is defined and branch in ['fea', 'feature', 'all']
  post_tasks:
    - shell: echo 'playbook memcached ends'
  vars:
- name: Install develop memcached
  hosts: dev-memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: dev
      when: branch is defined and branch in ['dev', 'develop', 'all']
  post_tasks:
    - shell: echo 'playbook memcached ends'

- name: Install master memcached
  hosts: dev-memcached
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook memcached starts'
  roles:
    - role: memcached
      vars:
        bra: mas
      when: branch is defined and branch in ['mas', 'master', 'all']
  post_tasks:
    - shell: echo 'playbook memcached ends'
