---

- name: install feature mha_node
  hosts: fea-mha_node
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.fea.yml
    - ./../group_vars/masterha.fea.yml
    - ./../group_vars/cluster_ndb.fea.yml
    - ./../group_vars/cluster_ndb_mgm.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，MHA Node 安装开始"
      shell: echo 'playbook mha_node starts'
  roles:
    - role: mha_node
      vars:
        bra: fea
      when: (branch is not defined or branch in ['fea', 'feature','all'] )
  post_tasks:
    - name: "本地 feature 环境，MHA Node 安装完毕"
      shell: echo 'playbook mha_node ends'

####################

    
- name: install develop mha_node
  hosts: dev-mha_node
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.dev.yml
    - ./../group_vars/masterha.dev.yml
    - ./../group_vars/cluster_ndb.dev.yml
    - ./../group_vars/cluster_ndb_mgm.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，MHA Node 安装开始"
      shell: echo 'playbook mha_node starts'
  roles:
    - role: mha_node
      vars:
        bra: dev
      when: (branch is defined and branch in ['dev', 'develop','all'] )
  post_tasks:
    - name: "开发 develop 环境，MHA Node 安装完毕"
      shell: echo 'playbook mha_node ends'
     
      
      
      
#############################################


- name: install release mha_node
  hosts: rel-mha_node
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.rel.yml
    - ./../group_vars/masterha.rel.yml
    - ./../group_vars/cluster_ndb.rel.yml
    - ./../group_vars/cluster_ndb_mgm.rel.yml
  pre_tasks:
    - name: "开发 release 环境，MHA Node 安装开始"
      shell: echo 'playbook mha_node starts'
  roles:
    - role: mha_node
      vars:
        bra: rel
      when: (branch is defined and branch in ['rel', 'release','all'] )
  post_tasks:
    - name: "开发 release 环境，MHA Node 安装完毕"
      shell: echo 'playbook mha_node ends'
