---

- name: install mmm_agent
  hosts: mmm_agent
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  vars_files:
    - ./../group_vars/mysql.{{ branch }}.yml
    - ./../group_vars/masterha.{{ branch }}.yml
    - ./../group_vars/cluster_ndb.{{ branch }}.yml
    - ./../group_vars/cluster_ndb_mgm.{{ branch }}.yml

  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "!!!!!!!!!!!!!!!!!!!!嚴重警告!!!!!!!!!!!!!!!!!!!!"
      pause:
        prompt: 確定 要在 master 環境下嗎? 後果自行負責!
      when: branch == 'mas'
    - name: "{{ branch }} mmm_agent 安装开始"
      shell: echo 'playbook mmm_agent starts'
  roles:
    - role: mmm_agent
      vars:
        bra: branch
  post_tasks:
    - name: "本地 feature 环境，MMM Agent 安装完毕"
      shell: echo 'playbook mmm_agent ends'

 


####################
