---

- name: install feature mmm_agent
  hosts: fea-mmm_agent
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.fea.yml
    - ./../group_vars/masterha.fea.yml
    - ./../group_vars/cluster_ndb.fea.yml
    - ./../group_vars/cluster_ndb_mgm.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，MMM Agent 安装开始"
      shell: echo 'playbook mmm_agent starts'
  roles:
    - role: mmm_agent
      vars:
        bra: fea
      when: (branch is not defined or branch in ['fea', 'feature','all'] )
  post_tasks:
    - name: "本地 feature 环境，MMM Agent 安装完毕"
      shell: echo 'playbook mmm_agent ends'

 


####################
