---

- name: install mmm_monitor
  hosts: mmm_monitor
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: "[單選] 你要運行在那種模式下 fea, dev, rel, mas ?"
      private: no
  vars_files:
    - ./../group_vars/mysql.{{ branch }}.yml
    - ./../group_vars/masterha.{{ branch }}.yml
    - ./../group_vars/cluster_ndb.{{ branch }}.yml
    - ./../group_vars/cluster_ndb_mgm.{{ branch }}.yml

  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
      pause:
        prompt: "[警告] 確定 要在 master 環境下嗎? 後果自行負責! (yes/no)"
      register: confirmation
      when: branch == 'mas'
    - name: "錯誤! 客戶端 終止"
      meta: end_play
      when:  branch == 'mas' and (confirmation is defined and confirmation.user_input is defined and confirmation.user_input != 'yes')
    - name: "{{ branch }} mmm_monitor 安装开始"
      shell: echo 'playbook mmm_monitor starts'
  roles:
    - role: mmm_monitor
      vars:
        bra: branch
  post_tasks:
    - name: "本地 feature 环境，MMM Monitor 安装完毕"
      shell: echo 'playbook mmm_monitor ends'    

####################