---
- name: install feature mysql
  hosts: fea-mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  vars_files:
    - ./../group_vars/mysql.fea.yml
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "本地 feature 环境，MySQL 安装开始"
      shell: echo 'playbook mysql starts'
      check_mode: no
  roles:
    - role: mysql
      vars:
        bra: fea
      when: (branch is not defined or branch in ['fea', 'feature', 'all'] )
  post_tasks:
    - name: "本地 feature 环境，MySQL 安装完毕"
      shell: echo 'playbook mysql ends'

####################

- name: install develop mysql
  hosts: dev-mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，MySQL 安装开始"
      shell: echo 'playbook mysql starts'
      check_mode: no
  roles:
    - role: mysql
      vars:
        bra: dev
      when: (branch is defined and branch in ['dev', 'develop', 'all'] )
  post_tasks:
    - name: "开发 develop 环境，MySQL 安装完毕"
      shell: echo 'playbook mysql ends'      
      
      
      
###################################################



- name: install release mysql
  hosts: rel-mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.rel.yml
  pre_tasks:
    - name: "开发 release 环境，MySQL 安装开始"
      shell: echo 'playbook mysql starts'
      check_mode: no
  roles:
    - role: mysql
      vars:
        bra: rel
      when: (branch is defined and branch in ['rel', 'release', 'all'] )
  post_tasks:
    - name: "开发 release 环境，MySQL 安装完毕"
      shell: echo 'playbook mysql ends'


- name: install master mysql
  hosts: mas-mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/mysql.mas.yml
  pre_tasks:
    - name: "开发 master 环境，MySQL 安装开始"
      shell: echo 'playbook mysql starts'
      check_mode: no
  roles:
    - role: mysql
      vars:
        bra: mas
      when: (branch is defined and branch in ['mas', 'master', 'all'] )
  post_tasks:
    - name: "开发 master 环境，MySQL 安装完毕"
      shell: echo 'playbook mysql ends'
