---
- name: install mysql
  hosts: mysql
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: "[單選] 你要運行在那種模式下 fea, dev, rel, mas ?"
      private: no
  vars_files:
    - ./../group_vars/mysql.{{ branch }}.yml
  pre_tasks:
    - name: "錯誤! mysql {{ mysql_version }} 不支持 MGR"
      shell: echo 'error'
      check_mode: no

    - name: "錯誤! mysql {{ mysql_version }} 不支持 MGR"
      meta: end_play
      when: (mysql_ha == 'mgr-primary' or mysql_ha == 'mgr-multiple') and (mysql_version == '5.6' or mysql_version == '5.5')

    - name: "inventory_file  = {{ inventory_file }}, inventory_file | regex_replace =  {{ inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2') }}, branch = {{ branch }}"
      shell: 'echo inventory_file'
      check_mode: no

    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
      pause:
        prompt: "[警告] 確定 要在 master 環境下嗎? 後果自行負責! (yes/no)"
      register: confirmation
      when: branch == 'mas'
    - name: "錯誤! 客戶端 終止"
      meta: end_play
      when:  branch == 'mas' and (confirmation is defined and confirmation.user_input is defined and confirmation.user_input != 'yes')

    - name: "{{ branch }} 环境，MySQL {{ mysql_ha }} 安装开始"
      shell: echo 'playbook mysql starts'
      check_mode: no
  roles:
    - role: mysql
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，MySQL {{ mysql_ha }} 安装完毕"
      shell: echo 'playbook mysql ends'