---
- name: Install feature nginx
  hosts: fea-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/nginx.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Nginx 安装开始"
      shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Nginx 安装开始"
      shell: echo 'playbook nginx ends'
  vars:
