---
- name: Install feature nginx
  hosts: nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/nginx.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Nginx 安装开始"
      shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      vars: 
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Nginx 安装开始"
      shell: echo 'playbook nginx ends'
  vars:
