---
- name: Install nginx
  hosts: nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: 你要運行在那種模式下 fea, dev, rel, mas ?
      private: no
  vars_files:
    - ./../group_vars/nginx.{{ branch }}.yml
  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "!!!!!!!!!!!!!!!!!!!!嚴重警告!!!!!!!!!!!!!!!!!!!!"
      pause:
        prompt: 確定 要在 master 環境下嗎? 後果自行負責!
      when: branch == 'mas'

    - name: "{{ branch }} 环境，MySQL 安装开始"
      shell: echo 'playbook nginx starts'
      check_mode: no
  roles:
    - role: nginx
      vars: 
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Nginx 安装开始"
      shell: echo 'playbook nginx ends'
  vars:
