---
- name: Install feature nginx
  hosts: fea-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/nginx.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Nginx 安装开始"
      shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Nginx 安装开始"
      shell: echo 'playbook nginx ends'
  vars:
- name: Install develop nginx
  hosts: dev-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/nginx.dev.yml
  pre_tasks:
    - name: "开发 devlop 环境，Nginx 安装开始"
      shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      vars:
        bra: dev
      when: branch is defined and branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 devlop 环境，Nginx 安装完毕"
      shell: echo 'playbook nginx ends'


- name: Install release nginx
  hosts: rel-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "开发 release 环境，Nginx 安装开始"
      shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      vars:
        bra: rel
      when: branch is defined and branch in ['rel', 'release', 'all']
  post_tasks:
    - name: "开发 release 环境，Nginx 安装完毕"
      shell: echo 'playbook nginx ends'
