---
- name: Install feature node
  hosts: node
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/node.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Node 安装开始"
      shell: echo 'playbook node starts'
  roles:
    - role: node
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Node 安装完毕"
      shell: echo 'playbook node ends'
