---
# PYTHON 这里有一个坑，Yum 指令 , Ansible 指令 都是相依於 PYTHON 
# 不可随意改变 python 版本，
# 请用 /usr/bin/python2 /usr/bin/python3

- name: "Install feature python"
  hosts: python # Ansible tower cannt remove or reinstall python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/python.fea.yml
    - ./../group_vars/supervisor.fea.yml
    - ./../group_vars/timedatectl.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Python 安装开始"
      shell: "echo 'playbook python starts' "
  roles:
    - role: python
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Python 安装完毕"
      shell: echo 'playbook python ends'
