---
# PYTHON 这里有一个坑，Yum 指令 , Ansible 指令 都是相依於 PYTHON 
# 不可随意改变 python 版本，
# 请用 /usr/bin/python2 /usr/bin/python3

- name: "Install feature python"
  hosts: fea-python # Ansible tower cannt remove or reinstall python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/python.fea.yml
    - ./../group_vars/supervisor.fea.yml
    - ./../group_vars/timedatectl.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Python 安装开始"
      shell: "echo 'playbook python starts' "
  roles:
    - role: python
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Python 安装完毕"
      shell: echo 'playbook python ends'
- name: Install develop python
  hosts: dev-python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/python.dev.yml
    - ./../group_vars/supervisor.dev.yml
    - ./../group_vars/timedatectl.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，Python 安装开始"
      shell: echo 'playbook python starts'
  roles:
    - role: python
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，Python 安装完毕"
      shell: echo 'playbook python ends'
