---
# PYTHON 这里有一个坑，Yum 指令 , Ansible 指令 都是相依於 PYTHON 
# 不可随意改变 python 版本，
# 请用 /usr/bin/python2 /usr/bin/python3

- name: "Install python"
  hosts: python # Ansible tower cannt remove or reinstall python
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_prompt:
    - name: branch
      prompt: "[單選] 你要運行在那種模式下 fea, dev, rel, mas ?"
      private: no
  vars_files:
    - ./../group_vars/python.{{ branch }}.yml
    - ./../group_vars/timedatectl.{{ branch }}.yml

  pre_tasks:
    - name: "錯誤! 指定 host 與 branch 不一致"
      meta: end_play
      when:  (inventory_file | regex_replace('([\\w\\-\\/])+.(\\w+)$', '\\2')) != branch
    - name: "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING"
      pause:
        prompt: "[警告] 確定 要在 master 環境下嗎? 後果自行負責! (yes/no)"
      register: confirmation
      when: branch == 'mas'
    - name: "錯誤! 客戶端 終止"
      meta: end_play
      when:  branch == 'mas' and confirmation.user_input != 'yes'
    - name: "{{ branch }} 环境，python 安装开始"
      shell: echo 'playbook python starts'
      check_mode: no
  roles:
    - role: python
      vars:
        bra: branch
  post_tasks:
    - name: "{{ branch }} 环境，Python 安装完毕"
      shell: echo 'playbook python ends'
