---
- name: Install feature rabbitmq
  hosts: fea-rabbitmq
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/rabbitmq.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq starts'
  roles:
    - role: rabbitmq
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq ends'
  vars:

- name: Install develop rabbitmq
  hosts: dev-rabbitmq
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/rabbitmq.dev.yml
  pre_tasks:
    - name: "本地 develop 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq starts'
  roles:
    - role: rabbitmq
      vars: 
        bra: dev
      when: branch is not defined or branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "本地 develop 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq ends'
  vars:


- name: Install release rabbitmq
  hosts: rel-rabbitmq
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/rabbitmq.rel.yml
  pre_tasks:
    - name: "本地 release 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq starts'
  roles:
    - role: rabbitmq
      vars: 
        bra: rel
      when: branch is not defined or branch in ['rel', 'release', 'all']
  post_tasks:
    - name: "本地 release 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq ends'
  vars:


- name: Install master rabbitmq
  hosts: mas-rabbitmq
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
  - ./../group_vars/rabbitmq.mas.yml
  pre_tasks:
    - name: "本地 master 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq starts'
  roles:
    - role: rabbitmq
      vars: 
        bra: mas
      when: branch is not defined or branch in ['mas', 'master', 'all']
  post_tasks:
    - name: "本地 master 环境，Rabbitmq 安装开始"
      shell: echo 'playbook Rabbitmq ends'
  vars:
