---
- name: Install feature redis
  hosts: fea-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.fea.yml
  pre_tasks:
    - name: '本地 feature 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: fea
      when: branch is defined and branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: '开发 feature 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'
  vars:
- name: Install develop redis
  hosts: dev-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.dev.yml
  pre_tasks:
    - name: '开发 develop 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: dev
      when: branch is defined and branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: '开发 develop 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'

- name: Install master redis
  hosts: mas-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.mas.yml
  pre_tasks:
    - name: '开发 master 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: mas
      when: branch is defined and branch in ['mas', 'master', 'all']
  post_tasks:
    - name: '开发 master 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'
