---
- name: Install feature redis
  hosts: fea-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.fea.yml
  pre_tasks:
    - name: '本地 feature 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - name: '开发 feature 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'
  vars:
- name: Install develop redis
  hosts: dev-redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.dev.yml
  pre_tasks:
    - name: '开发 develop 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - name: '开发 develop 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'
