---
- name: Install feature redis
  hosts: redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/redis.fea.yml
  pre_tasks:
    - name: '本地 feature 环境，Redis 安装开始'
      shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: branch
  post_tasks:
    - name: '开发 feature 环境，Redis 安装完毕'
      shell: echo 'playbook redis ends'
  vars: