---
- name: Install feature shoushou_video git
  hosts: shoushou_video-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 1
        nginx: 0
        mysql: 0
        rabbitmq: 0
        supervisor: 0
        mongodb: 0
  post_tasks:
    - name: "本地 feature 环境，shoushou_video 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'git'


- name: Install feature shoushou_video nginx
  hosts: shoushou_video-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video nginx 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 0
        nginx: 1
        mysql: 0
        rabbitmq: 0
        supervisor: 0
        mongodb: 0
  post_tasks:
    - name: "本地 feature 环境，shoushou_video nginx 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'nginx'

- name: Install feature shoushou_video mysql
  hosts: shoushou_video-mysql
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video mysql 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 0
        nginx: 0
        mysql: 1
        rabbitmq: 0
        supervisor: 0
        mongodb: 0
  post_tasks:
    - name: "本地 feature 环境，shoushou_video mysql 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'mysql'


- name: Install feature shoushou_video rabbitmq
  hosts: shoushou_video-rabbitmq
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video rabbitmq 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 0
        nginx: 0
        mysql: 0
        rabbitmq: 1
        supervisor: 0
        mongodb: 0

  post_tasks:
    - name: "本地 feature 环境，shoushou_video rabbitmq 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'rabbitmq'


- name: Install feature shoushou_video supervisor
  hosts: shoushou_video-supervisor
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video supervisor 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 0
        nginx: 0
        mysql: 0
        rabbitmq: 0
        supervisor: 1
        mongodb: 0

  post_tasks:
    - name: "本地 feature 环境，shoushou_video supervisor 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'supervisor'
- name: Install feature shoushou_video mongodb
  hosts: shoushou_video-mongodb
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video mongodb 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: branch
        git: 0
        nginx: 0
        mysql: 0
        rabbitmq: 0
        supervisor: 0
        mongodb: 1

  post_tasks:
    - name: "{{ branch }} 环境，shoushou_video mongodb 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'mongodb'


      