---
- name: Install feature shoushou_video git
  hosts: fea-shoushou_video-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: fea
        git: 1
        nginx: 0
        mysql: 0
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，shoushou_video 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'git'


- name: Install feature shoushou_video nginx
  hosts: fea-shoushou_video-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video nginx 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: fea
        git: 0
        nginx: 1
        mysql: 0
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，shoushou_video nginx 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'nginx'

- name: Install feature shoushou_video mysql
  hosts: fea-shoushou_video-mysql
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.fea.yml
  pre_tasks:
    - name: "本地 feature shoushou_video mysql 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: fea
        git: 0
        nginx: 0
        mysql: 1
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，shoushou_video mysql 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'mysql'


      




- name: Install develop shoushou_video all
  hosts: dev-shoushou_video
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.dev.yml
  pre_tasks:
    - name: "本地 develop shoushou_video 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars:
        bra: dev
        git: 1
        nginx: 1
        mysql: 1
      when: branch is not defined or branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "本地 develop 环境，shoushou_video 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'git'
    - 'mysql'
    - 'nginx'


      
- name: Install master shoushou_video GIT
  hosts: mas-shoushou_video-git
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.mas.yml
  pre_tasks:
    - name: "本地 master shoushou_video GIT 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars: 
        bra: mas
        git: 1
        nginx: 0
        mysql: 0
      when: branch is not defined or branch in ['mas', 'master', 'all']
  post_tasks:
    - name: "本地 master shoushou_video GIT 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'git'


- name: Install master shoushou_video NGINX
  hosts: mas-shoushou_video-nginx
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.mas.yml
  pre_tasks:
    - name: "本地 master shoushou_video NGINX 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars: 
        bra: mas
        git: 0
        nginx: 1
        mysql: 0
      when: branch is not defined or branch in ['mas', 'master', 'all']
  post_tasks:
    - name: "本地 master shoushou_video NGINX 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'nginx'


- name: Install master shoushou_video MYSQL
  hosts: mas-shoushou_video-mysql
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/shoushou_video.mas.yml
  pre_tasks:
    - name: "本地 master shoushou_video MYSQL 安装开始"
      shell: echo 'playbook shoushou_video starts'
  roles:
    - role: shoushou_video
      vars: 
        bra: mas
        git: 0
        nginx: 0
        mysql: 1
      when: branch is not defined or branch in ['mas', 'master', 'all']
  post_tasks:
    - name: "本地 master shoushou_video MYSQL 安装完毕"
      shell: echo 'playbook shoushou_video ends'
  tags:
    - 'mysql'