---
- name: Install feature supervisor
  hosts: fea-supervisor
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - name: "本地 feature 环境，Supervisor 安装开始"
      shell: echo 'playbook supervisor starts'
  roles:
    - role: supervisor
      vars: 
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Supervisor 安装开始"
      shell: echo 'playbook supervisor ends'
  vars: