---
- name: "Install feature supervisor"
  hosts: fea-supervisor
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/supervisor.fea.yml
  pre_tasks:
    - name: "本地 feature 环境，Python 安装开始"
      shell: "echo 'playbook supervisor starts' "
  roles:
    - role: supervisor
      vars:
        bra: fea
      when: branch is not defined or branch in ['fea', 'feature', 'all']
  post_tasks:
    - name: "本地 feature 环境，Python 安装开始"
      shell: echo 'playbook supervisor ends'
- name: Install develop supervisor
  hosts: dev-supervisor
  strategy: linear # free, debug
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/supervisor.dev.yml
  pre_tasks:
    - name: "开发 develop 环境，Python 安装开始"
      shell: echo 'playbook supervisor starts'
  roles:
    - role: supervisor
      vars:
        bra: dev
      when: branch in ['dev', 'develop', 'all']
  post_tasks:
    - name: "开发 develop 环境，Python 安装开始"
      shell: echo 'playbook supervisor ends'
