---
- name: install feature xtrabackup
  hosts: fea-xtrabackup
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/xtrabackup.fea.yml
  pre_tasks:
    - shell: echo 'playbook xtrabackup starts'
  roles:
    - role: xtrabackup
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook xtrabackup ends'