---
- name: install feature xtrabackup
  hosts: xtrabackup
  strategy: linear # free, debug
  serial:
    - 10
    - 50%
  gather_facts: true
  become: true
  vars_files:
    - ./../group_vars/xtrabackup.fea.yml
  pre_tasks:
    - shell: echo 'playbook xtrabackup starts'
  roles:
    - role: xtrabackup
      vars:
        bra: branch
  post_tasks:
    - shell: echo 'playbook xtrabackup ends'