---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: (yum) yum install memcached
  yum:
    name: memcached
    state: latest
- name: (shell) memcached -h
  shell: memcached -h
  register: memcached_version_string
- name: (debug) memcached_version_string
  debug: 
    msg: "{{ memcached_version_string }}"