---
- name: "(shell) php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }} -v"
  shell: "php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }} -v"
  register: s_php_version
- name: (debug) s_php_version
  debug: 
    msg: "{{ s_php_version }}"